### ISSUE TITLE
Ideas and thoughts

### ISSUE THREAD

**Issue by Husteln** [Geuthur/aa-ledger#26]
Hi there!

Thanks for the tool, been looking for something like it for some time, since we had something like that long time ago, but built purely on PHP.

So, my thoughts:

1. Per-member daily/monthly graphs - because overall graphs are good, but knowing who is consistently krabbing over periods of time is also useful. 
2. Hourly statistics? Because it is also useful to know if a member is krabbing when he/she ideally should not (stratops)
4. Access all characters in 'character ledger' - I am a superuser and still I am not able to view anything but my chars (which have no krabbing data) - bug?
5. AVGs calculation. Judging by the values, I have a feeling (did not look at the code for it yet) that its a very simple calculation, like total sum x 3 (because tick per 20 min) / total num of hours in the period (say, month). Hence the values are so much less than you would expect. IIRC 
I used to calculate this using only number of ticks, where 3 ticks roughly equal to 1 hour, so the ticks/amounts are summed on hourly bases (coming from tick datetime), divided by 3 and then averaged up.
6. Agent mission payouts. Yes, the values are very low and no one would really care, but it is in itself an indicator of someone doing agent missions. Probably it could be the amount and/or number of missions done? Still better than nothing

**Comment by Geuthur** [comment]
Hi,

Thanks for you  Suggestion.

1. I will notice that and will work on this beside
2. There are Hourly Statistics on the Information button the main problem about this why i dont have done this already is the ESI only update Wallet Information every 2 hours so it make normally no sense to do so
3. This is for sure on the TODO ;) I have already prepared this in the code ^^ this feature will come in the coming versions
4. I am not sure but AVG Calculation already on the Template View or you main more specific one?
5. I will add this filter

**Comment by Husteln** [comment]
For p, 4, AVG calculation, I mean numbers on the screenshot attached.

As per code from template_manager.py:
```
      "average_hour": round(
          (amounts[key]["total_amount"] / current_day) / 24, 2
```
In here you calculate AVG in a simple way, using total amounts krabbed and number of hours in a day.

I suggest to calculate it differently, using scheme described in my original post. Knowing that each 'tick' (wallet journal entry) rougly equals 20 min of krabbing (because people do not always spend 20 minutes krabbing - start and finish perioud), you could get avg values which are really close to what people actually get - isk per hour. Or per tick
![image](https://github.com/user-attachments/assets/0b5b00f6-d462-4e72-b600-5ead8457b2a9)
