### ISSUE TITLE
[Featured Request] ledger extension

### ISSUE THREAD

**Issue by GurkeTonic** [Geuthur/aa-ledger#45]
Is there a way to extend the ledger with the Ref_Type: corporate_reward_payout

Members who fly to Pochven to “rat” there or fly to Incursions receive the payout via this Ref_Type

**Comment by Geuthur** [comment]
Hey @GurkeTonic,

I will add this to the next version thanks for you suggestion.

Cheers
Geuthur

**Comment by Geuthur** [comment]
@GurkeTonic can you tell me is it on the corporation or the characterjournal

**Comment by GurkeTonic** [comment]
@Geuthur corporate_reward_payout is in both, character and corpjournal.
![characterwalletjournalentry](https://github.com/user-attachments/assets/22cdfa09-9a08-4700-b1d4-1a2bc2206378)
![corporationwalletjournalentry](https://github.com/user-attachments/assets/a8c736d5-3070-482b-8973-022c7cec402c)
