### ISSUE TITLE
Feature: aa-charlink integration

### ISSUE THREAD

**Issue by digital-pet** [Geuthur/aa-ledger#48]
Instructions below:

> From version 1.1.0, CharLink supports hook integration. If you want to integrate your app with CharLink, you need to register a hook in the auth_hooks.py file:
> 
> ```
> @hooks.register('charlink')
> def register_charlink_hook():
>    return 'testauth.testapp.charlink_hook'
> ```
> 
> The hook has to return a string with the import path of the module containing the app integration. The module must contain a variable called app_import which is an instance of charlink.app_imports.utils.AppImport. You can find the documentation of the class in the [utils.py](https://github.com/Maestro-Zacht/aa-charlink/blob/main/charlink/app_imports/utils.py) and some examples in the [imports folder](https://github.com/Maestro-Zacht/aa-charlink/blob/main/charlink/imports).

**Comment by Geuthur** [comment]
I am not sure what i need to do but i made a integration and tested it with charlink and it works.

I will write the dev and then add it to the ledger
